#ifndef RPT_TOPICIDS_H
#define RPT_TOPICIDS_H

#define CFE_MISSION_RPT_CMD_TOPICID         0x63
#define CFE_MISSION_RTP_SEND_BCN_TOPICID    0x64
#define CFE_MISSION_RPT_SEND_HK_TOPICID     0x65


#define CFE_MISSION_BCN_TLM_TOPICID         0x60
#define CFE_MISSION_HK_TLM_TOPICID          0x61

#define CFE_MISSION_RPT_REPORT_TOPICID      0x62
#define CFE_MISSION_RPT_CRITICAL_TOPICID    0x63

#endif