#ifndef RPT_MSGIDS_H
#define RPT_MSGIDS_H

#include "cfe_core_api_base_msgids.h"
#include "rpt_topicids.h"

/**
 * For Telecommand handling
 */
#define RPT_CMD_MID             CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_RPT_CMD_TOPICID)
#define RPT_SEND_BCN_MID        CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_RTP_SEND_BCN_TOPICID)
#define RPT_SEND_HK_MID         CFE_PLATFORM_CMD_TOPICID_TO_MIDV(CFE_MISSION_RPT_SEND_HK_TOPICID)


/**
 * For Telemetry publishing
 */
#define RPT_BCN_TLM_MID         CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_BCN_TLM_TOPICID)
#define RPT_HK_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_HK_TLM_TOPICID)


/**
 * For Report Msg publishing
 */
#define RPT_REPORT_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_RPT_REPORT_TOPICID)
#define RPT_CRITICAL_TLM_MID    CFE_PLATFORM_TLM_TOPICID_TO_MIDV(CFE_MISSION_RPT_CRITICAL_TOPICID)

#endif